"use client";
import {useEffect,useRef,useState} from "react";
import {Gamepad2,Brain,Grid3X3,RotateCcw,Trophy,HelpCircle} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {boardResult,shuffle,foodCards,foodQuestions,type Mark} from "@/lib/table-games";
type Game="memory"|"quiz"|"tictactoe";
const titles={memory:"Foodie memory",quiz:"The food quiz",tictactoe:"Table tic-tac-toe"};
export default function TableGames(){
 const [open,setOpen]=useState(false),[game,setGame]=useState<Game|null>(null);
 const games=[{id:"memory" as const,icon:Brain,name:titles.memory,tag:"SOLO OR TAKE TURNS",detail:"Find all 6 matching food pairs."},{id:"quiz" as const,icon:HelpCircle,name:titles.quiz,tag:"5 QUICK QUESTIONS",detail:"How well do you know your food?"},{id:"tictactoe" as const,icon:Grid3X3,name:titles.tictactoe,tag:"2 PLAYERS · ONE PHONE",detail:"Challenge someone at your table."}];
 return <><section className="waiting-invite"><Gamepad2 size={25}/><div><h2>Food on the way?</h2><p>A little table-time fun while you wait.</p></div><button className="secondary" onClick={()=>{setGame(null);setOpen(true)}}>Play a quick game</button></section><Dialog open={open} onOpenChange={setOpen}><DialogContent className="games-modal"><p className="eyebrow">THE TABLE ARCADE</p><DialogTitle>{game?titles[game]:"Good company. Great little games."}</DialogTitle><DialogDescription>{game==="tictactoe"?"Take turns on this phone. Get three in a row to win.":game==="memory"?"Flip two cards at a time. Match every pair in as few moves as you can.":game==="quiz"?"Pick an answer, discover a food fact, and see your score.":"No download needed. Pick a game and make the wait more fun."}</DialogDescription>{game?<><button className="game-back" onClick={()=>setGame(null)}>All games</button>{game==="memory"?<MemoryGame/>:game==="quiz"?<FoodQuiz/>:<TicTacToe/>}</>:<div className="game-choices">{games.map(g=><button key={g.id} onClick={()=>setGame(g.id)}><span className="game-icon"><g.icon size={23}/></span><span><small>{g.tag}</small><strong>{g.name}</strong><span>{g.detail}</span></span></button>)}</div>}<p className="game-footnote">Just for fun. No prizes or discounts. Closing the game resets this round.</p></DialogContent></Dialog></>;
}
function MemoryGame(){
 const [cards,setCards]=useState(()=>shuffle([...foodCards,...foodCards])),[flipped,setFlipped]=useState<number[]>([]),[matched,setMatched]=useState<number[]>([]),[moves,setMoves]=useState(0),[message,setMessage]=useState("Choose your first two cards.");const timer=useRef<ReturnType<typeof setTimeout>|null>(null),locked=useRef(false);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 function reset(){if(timer.current)clearTimeout(timer.current);locked.current=false;setCards(shuffle([...foodCards,...foodCards]));setFlipped([]);setMatched([]);setMoves(0);setMessage("Fresh cards. Find your first pair.")}
 function flip(index:number){if(locked.current||flipped.includes(index)||matched.includes(index))return;const next=[...flipped,index];setFlipped(next);if(next.length===2){locked.current=true;setMoves(m=>m+1);const [a,b]=next;if(cards[a].name===cards[b].name){setMatched(m=>[...m,a,b]);setMessage(matched.length===10?"All six pairs found!":"A match! Find another pair.");setFlipped([]);locked.current=false;}else{setMessage("Not a match. Take a look and try again.");timer.current=setTimeout(()=>{setFlipped([]);locked.current=false;setMessage("Choose two more cards.")},1000);}}}
 const complete=matched.length===12;
 return <div><div className="game-score"><span>Pairs <strong>{matched.length/2}/6</strong></span><span>Moves <strong>{moves}</strong></span></div><div className="memory-board">{cards.map((card,i)=>{const showing=flipped.includes(i)||matched.includes(i);return <button className={`memory-card ${showing?"revealed":""} ${matched.includes(i)?"matched":""}`} disabled={matched.includes(i)||complete} aria-label={showing?`${card.name}${matched.includes(i)?", matched":""}`:`Face-down card ${i+1}`} aria-pressed={showing} key={i} onClick={()=>flip(i)}><span aria-hidden="true">{showing?card.icon:"?"}</span></button>})}</div><p className="game-message" role="status">{message}</p>{complete&&<div className="game-win"><Trophy size={25}/><strong>Six pairs. Nicely done!</strong><p>You finished in {moves} moves.</p></div>}<button className="secondary" onClick={reset}><RotateCcw size={16}/>{complete?"Play again":"Restart game"}</button></div>
}
function TicTacToe(){const [board,setBoard]=useState<Mark[]>(Array(9).fill(null)),[turn,setTurn]=useState<"X"|"O">("X");const result=boardResult(board);function reset(){setBoard(Array(9).fill(null));setTurn("X")}
 return <div><p className="game-message turn-message" role="status">{result.winner?`Player ${result.winner} wins!`:result.draw?"It’s a draw. Rematch?":`Player ${turn}’s turn`}</p><div className="ttt-board">{board.map((mark,i)=><button className={`${mark==="O"?"mark-o":""} ${result.line.includes(i)?"winning-cell":""}`} key={i} disabled={!!mark||!!result.winner||result.draw} aria-label={`Row ${Math.floor(i/3)+1}, column ${i%3+1}: ${mark||"empty"}`} onClick={()=>{if(board[i]||result.winner||result.draw)return;setBoard(b=>b.map((v,j)=>j===i?turn:v));setTurn(t=>t==="X"?"O":"X")}}>{mark}</button>)}</div><button className="secondary" onClick={reset}><RotateCcw size={16}/>{result.winner||result.draw?"Play again":"Restart game"}</button></div>}
function FoodQuiz(){const [questions,setQuestions]=useState(()=>shuffle(foodQuestions).slice(0,5)),[index,setIndex]=useState(0),[answer,setAnswer]=useState<number|null>(null),[score,setScore]=useState(0),[finished,setFinished]=useState(false);const picked=useRef(false);const q=questions[index];function reset(){setQuestions(shuffle(foodQuestions).slice(0,5));setIndex(0);setAnswer(null);setScore(0);setFinished(false);picked.current=false;}
 if(finished)return <div className="quiz-finish"><Trophy size={40}/><h3>{score===5?"A proper foodie!":score>=3?"You know your food!":"A few new food facts to share."}</h3><p className="quiz-big-score">{score}<span>/5</span></p><p>Fancy another round?</p><button className="primary" onClick={reset}><RotateCcw size={16}/>Play again</button></div>;
 return <div><div className="game-score"><span>Question <strong>{index+1}/5</strong></span><span>Score <strong>{score}</strong></span></div><h3 className="food-question">{q.question}</h3><div className="food-answers">{q.choices.map((c,i)=><button key={i} disabled={answer!==null} className={answer!==null&&i===q.answer?"correct":answer===i?"incorrect":""} onClick={()=>{if(picked.current)return;picked.current=true;setAnswer(i);if(i===q.answer)setScore(s=>s+1)}}><span>{String.fromCharCode(65+i)}</span>{c}{answer!==null&&i===q.answer&&<small>Correct answer</small>}</button>)}</div>{answer!==null&&<div className="answer-feedback" role="status"><strong>{answer===q.answer?"That’s right!":"Now you know!"}</strong><p>{q.explanation}</p><button className="primary" onClick={()=>{if(index===4)setFinished(true);else{setIndex(i=>i+1);setAnswer(null);picked.current=false;}}}>{index===4?"See my score":"Next question"}</button></div>}</div>;
}
