"use client";
import {useEffect,useRef,useState} from "react";
import {Bell,Volume2} from "lucide-react";
import type {StoredOrder} from "@/lib/orders";
export default function OrderAlerts({managerOnly=false,onOpen}:{managerOnly?:boolean,onOpen?:(restaurant:string)=>void}){
 const [orders,setOrders]=useState<StoredOrder[]>([]),[error,setError]=useState(""),[sound,setSound]=useState(false),[last,setLast]=useState("");const seen=useRef<Set<string>>(new Set()),audio=useRef<AudioContext|null>(null),enabled=useRef(false),initial=useRef(true);
 useEffect(()=>{let alive=true;async function poll(){try{const r=await fetch(`/api/orders?alerts=1${managerOnly?"&scope=manage":""}`);const d=await r.json() as {orders:StoredOrder[],error?:string};if(!r.ok)throw Error(d.error);if(!alive)return;const fresh=d.orders.filter(o=>!seen.current.has(o.id));if(fresh.length&&(!initial.current||enabled.current)&&enabled.current&&audio.current){try{const a=audio.current;await a.resume();const osc=a.createOscillator(),gain=a.createGain();osc.connect(gain);gain.connect(a.destination);osc.frequency.value=740;gain.gain.setValueAtTime(.12,a.currentTime);gain.gain.exponentialRampToValueAtTime(.001,a.currentTime+.45);osc.start();osc.stop(a.currentTime+.45);}catch{enabled.current=false;setSound(false)}}d.orders.forEach(o=>seen.current.add(o.id));initial.current=false;setOrders(d.orders);setError("");setLast(new Date().toLocaleTimeString("en-IN"));}catch(e){if(alive){setError(e instanceof Error?e.message:"Alerts disconnected");if((e as Error).message?.includes("access"))setOrders([])}}}poll();const t=setInterval(poll,8000);function focus(){poll()}window.addEventListener("focus",focus);return()=>{alive=false;clearInterval(t);window.removeEventListener("focus",focus);audio.current?.close();audio.current=null}},[managerOnly]);
 async function toggle(){if(enabled.current){enabled.current=false;setSound(false);return}try{if(!audio.current)audio.current=new AudioContext();await audio.current.resume();enabled.current=true;setSound(true)}catch{setError("Sound isn’t available in this browser. Visual alerts remain on.")}}
 return <div className={orders.length?"order-alert-banner has-orders":"order-alert-banner"}><Bell size={20}/><div aria-live="polite"><strong>{error?"Order alerts need attention":orders.length?`${orders.length}${orders.length===50?"+":""} new ${orders.length===1?"order":"orders"}`:"Listening for new orders"}</strong><p>{error||`Checks every 8 seconds while this page is open.${last?` Last checked ${last}.`:""}`}</p>{orders.length>0&&<div className="order-alert-links">{[...new Map(orders.map(o=>[o.restaurant_id,o])).values()].map(o=><button key={o.restaurant_id} onClick={()=>onOpen?.(o.restaurant_id)}>{o.restaurant_name} · {orders.filter(x=>x.restaurant_id===o.restaurant_id).length} new</button>)}</div>}</div><button className="secondary" onClick={toggle}><Volume2 size={16}/>{sound?"Sound on":"Enable sound"}</button></div>
}
