"use client";
import {useEffect,useState} from "react";
import {Plus,Users,Copy} from "lucide-react";
import {toast} from "sonner";
export default function RestaurantAccess({restaurant,name}:{restaurant:string,name:string}){
 const [members,setMembers]=useState<{email:string}[]>([]),[email,setEmail]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const r=await fetch(`/api/restaurant-access?restaurant=${encodeURIComponent(restaurant)}`);const d=await r.json() as {error?:string,members:{email:string}[]};if(!r.ok)throw Error(d.error);setMembers(d.members);setError("")}catch(e){setError(e instanceof Error?e.message:"Couldn’t load access")}finally{setLoading(false)}}
 useEffect(()=>{load()},[restaurant]);
 async function change(address:string,action:"add"|"remove"){setBusy(true);setError("");try{const r=await fetch("/api/restaurant-access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({restaurant,email:address,action})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);if(action==="add")setEmail("");await load();toast.success(action==="add"?`Access added for ${address.trim().toLowerCase()}`:"Restaurant access removed")}catch(e){setError(e instanceof Error?e.message:"Couldn’t update access")}finally{setBusy(false)}}
 return <div className="form-panel restaurant-access-panel"><span className="access-badge"><Users size={18}/> THIS RESTAURANT ONLY</span><h2>Who can manage {name}?</h2><p>Add the Gmail or other email address they use to sign in. They can edit this restaurant’s menu, prices, availability and details, and download its QR code.</p><form onSubmit={e=>{e.preventDefault();change(email,"add")}}><label>Restaurant manager’s sign-in email<input required type="email" maxLength={254} disabled={busy} value={email} onChange={e=>setEmail(e.target.value)} placeholder="Enter email"/></label><button type="submit" className="primary" disabled={busy||loading}><Plus size={16}/>{busy?"Updating…":"Give restaurant access"}</button></form>{error&&<div className="error" role="alert">{error}<button disabled={busy} onClick={load}>Retry</button></div>}<div className="access-instructions"><strong>How they sign in</strong><ol><li>Share the team dashboard link with them.</li><li>They sign in through ChatGPT using the email you added.</li><li>The dashboard shows only their assigned restaurants.</li></ol><button className="secondary" onClick={()=>navigator.clipboard.writeText(location.origin+"/team").then(()=>toast.success("Dashboard link copied")).catch(()=>toast.error("Copy the /team address from your browser."))}><Copy size={16}/>Copy dashboard link</button><p>The site is currently private. Also allow this email in the site’s sharing settings before they can open the link. Adding an email here does not send an invitation or change site sharing.</p></div><h3>Restaurant managers</h3>{loading?<p role="status">Loading access…</p>:members.length===0?<p className="muted">No restaurant managers added yet.</p>:members.map(m=><div className="member-row" key={m.email}><span>{m.email}</span><button disabled={busy} onClick={()=>change(m.email,"remove")}>Remove access</button></div>)}<p className="access-note">AS 426 Studios team members already have access to all restaurants. Removing someone here only removes this restaurant assignment; any studio-wide access remains.</p></div>
}
