"use client";
import {useEffect,useState} from 'react';
import {indiaDate} from '@/lib/order-time';
import {money} from '@/lib/orders';
type Report={month:string,orders:number,revenue:number,days:{day:string,orders:number,revenue:number}[]};
export default function Sales({restaurant}:{restaurant:string}){
 const [month,setMonth]=useState(indiaDate().slice(0,7)),[manual,setManual]=useState(false),[data,setData]=useState<Report|null>(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;async function load(){try{const current=indiaDate().slice(0,7);if(!manual&&current!==month){setMonth(current);return}const r=await fetch(`/api/sales?restaurant=${encodeURIComponent(restaurant)}&month=${month}`);const d=await r.json() as Report&{error?:string};if(!r.ok)throw Error(d.error);if(alive){setData(d);setError('')}}catch(e){if(alive){setData(null);setError(e instanceof Error?e.message:'Unable to load report')}}}setData(null);load();const t=setInterval(load,15000);return()=>{alive=false;clearInterval(t)}},[restaurant,month,manual]);
 const max=Math.max(1,...(data?.days.map(d=>d.revenue)||[]));
 return <section><div className="list-heading"><div><h2>Monthly sales</h2><p>Delivered orders, grouped by delivery date in India time.</p></div><label>Month<input type="month" min="2020-01" max="2100-12" value={month} onChange={e=>{if(e.target.value){setManual(true);setMonth(e.target.value)}}}/></label><button className="secondary" onClick={()=>{setManual(false);setMonth(indiaDate().slice(0,7))}}>Current month</button></div>{error&&<p className="error" role="alert">{error}</p>}{!data&&!error&&<p>Loading report…</p>}{data&&<><div className="stats"><div><span>Delivered orders</span><strong>{data.orders}</strong></div><div><span>Sales value</span><strong>{money(data.revenue)}</strong></div></div><p className="muted">This is the menu value of delivered orders, not verified payment collections or profit. Pending and cancelled orders are excluded. Previous months stay available.</p><div className="sales-chart" role="img" aria-label={`Daily sales for ${month}: ${data.orders} delivered orders, ${money(data.revenue)} total. Detailed figures below.`}>{data.days.map(d=><div className="sales-column" key={d.day} title={`${d.day}: ${d.orders} orders, ${money(d.revenue)}`}><div className="sales-bar-track"><div className="sales-bar" style={{height:`${d.revenue/max*100}%`}}/></div><span>{Number(d.day.slice(-2))}</span></div>)}</div>{data.orders===0&&<p>No delivered orders in this month yet.</p>}<details className="sales-details"><summary>Daily figures</summary><table><thead><tr><th>Date</th><th>Delivered orders</th><th>Sales value</th></tr></thead><tbody>{data.days.map(d=><tr key={d.day}><td>{d.day}</td><td>{d.orders}</td><td>{money(d.revenue)}</td></tr>)}</tbody></table></details></>}</section>
}
