"use client";
import {useEffect,useState} from "react";
import {Plus,Copy,Users} from "lucide-react";
type Waiter={email:string,name:string};
export default function Waiters({restaurant}:{restaurant:string}){
 const [rows,setRows]=useState<Waiter[]>([]),[name,setName]=useState(""),[email,setEmail]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(true),[success,setSuccess]=useState("");
 async function load(){setLoading(true);try{const r=await fetch(`/api/waiters?restaurant=${encodeURIComponent(restaurant)}`),d=await r.json() as {error?:string,waiters:Waiter[]};if(!r.ok)throw Error(d.error);setRows(d.waiters)}catch(e){setError(e instanceof Error?e.message:"Couldn’t load waiters")}finally{setLoading(false)}}useEffect(()=>{load()},[restaurant]);
 async function change(address:string,action:"add"|"remove"){setBusy(true);setError("");setSuccess("");try{const r=await fetch("/api/waiters",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({restaurant,email:address,name,action})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setName("");setEmail("");setSuccess(action==="add"?"Waiter access saved. Share the orders link with them.":"Waiter access removed.");await load()}catch(e){setError(e instanceof Error?e.message:"Couldn’t update waiter")}finally{setBusy(false)}}
 return <div className="form-panel"><span className="access-badge"><Users size={18}/> ORDERS-ONLY ACCESS</span><h2>Manage waiters</h2><p>Waiters can see this restaurant’s orders and alerts, accept pending orders, and confirm delivery of prepared orders. They cannot edit menus, manage staff, view sales reports or read reviews.</p><form onSubmit={e=>{e.preventDefault();change(email,"add")}}><label>Waiter’s name<input required maxLength={80} value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label><label>Sign-in email<input required type="email" maxLength={254} value={email} disabled={busy} onChange={e=>setEmail(e.target.value)} placeholder="waiter@gmail.com"/></label><button className="primary" disabled={busy}><Plus size={16}/>{busy?"Saving…":"Save waiter access"}</button></form>{error&&<p className="error" role="alert">{error}</p>}{success&&<p className="success-note" role="status">{success}</p>}<div className="access-instructions"><strong>Waiter login</strong><p>They sign in through ChatGPT using this email. While the site is private, also allow the email in the site’s sharing settings. No invitation is sent automatically.</p><button className="secondary" onClick={()=>navigator.clipboard.writeText(location.origin+"/team/orders").then(()=>setSuccess("Orders-only link copied.")).catch(()=>setError("Copy the site address followed by /team/orders."))}><Copy size={16}/>Copy waiter login link</button></div>{loading?<p>Loading waiters…</p>:!rows.length?<p className="muted">No waiters added yet.</p>:rows.map(w=><div className="member-row" key={w.email}><div><strong>{w.name}</strong><small className="waiter-email">{w.email}</small></div><div className="waiter-actions"><button disabled={busy} onClick={()=>{setName(w.name);setEmail(w.email);setSuccess("Edit the name above and save to update this waiter.")}}>Edit</button><button disabled={busy} onClick={()=>change(w.email,"remove")}>Remove access</button></div></div>)}</div>
}
