"use client";
import {useState,useRef} from "react";
import {Star,MessageSquare,CheckCircle2,Utensils} from "lucide-react";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
export default function ReviewForm({restaurant,name}:{restaurant:string,name:string}){
 const [rating,setRating]=useState(""),[message,setMessage]=useState(""),[guest,setGuest]=useState(""),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState("");const requestId=useRef("");
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;if(!rating){setError("Please choose a star rating.");return}setBusy(true);setError("");if(!requestId.current)requestId.current=crypto.randomUUID();try{const r=await fetch("/api/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:requestId.current,restaurant,rating:Number(rating),message,name:guest})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setSent(true)}catch(e){setError(e instanceof Error?e.message:"Couldn’t send your review. Please try again.")}finally{setBusy(false)}}
 return <main className="customer review-page"><header className="brandbar"><span className="brand"><span className="brandmark"><Utensils size={20}/></span>TABLE SECRET</span><a className="quiet-link" href={"/r/"+restaurant}>Back to menu</a></header><section className="review-sheet">{sent?<div className="review-sent" role="status"><CheckCircle2 size={48}/><p className="eyebrow">THANK YOU</p><h1>Your voice matters.</h1><p>Your review has been sent to the {name} management team.</p><a className="primary" href={"/r/"+restaurant}>Back to your menu</a></div>:<><span className="access-badge"><MessageSquare size={18}/> A NOTE TO THE RESTAURANT</span><h1>How was your experience?</h1><p className="review-intro">Share your thoughts with <strong>{name}</strong>. Your rating and message go privately to the restaurant’s management team.</p><form onSubmit={submit}><fieldset disabled={busy}><legend>Your rating</legend><RadioGroup className="review-stars" value={rating} onValueChange={setRating} aria-label="Your rating" required>{[1,2,3,4,5].map(n=><label key={n} className={Number(rating)>=n?"lit":""}><RadioGroupItem className="sr-only" value={String(n)} aria-label={`${n} ${n===1?"star":"stars"}`}/><Star size={32} fill={Number(rating)>=n?"currentColor":"none"}/><span>{n}</span></label>)}</RadioGroup><p className="rating-caption" aria-live="polite">{rating?["","Poor","Fair","Good","Very good","Excellent"][Number(rating)]:"Choose 1–5 stars"}</p><label>Your message<textarea required minLength={3} maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="What did you enjoy? What could we do better?"/></label><small className="review-counter">{message.length}/2,000</small><label>Your name <span className="muted">(optional)</span><input maxLength={80} value={guest} onChange={e=>setGuest(e.target.value)} placeholder="Leave blank to send anonymously" autoComplete="given-name"/></label></fieldset>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" type="submit" disabled={busy}>{busy?"Sending…":"Send review to restaurant"}</button><p className="review-privacy">This is private feedback, not a public or Google review. Please avoid including sensitive personal information.</p></form></>}</section><footer>Restaurant experiences by AS 426 Studios</footer></main>
}
