"use client";
import {useState} from "react";
import {Sparkles,Flame,Leaf} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {recommend} from "@/lib/recommend";
import type {Menu,Dish} from "@/lib/menu";
export default function TasteQuiz({menu,onPick}:{menu:Menu,onPick:(d:Dish)=>void}){
 const [open,setOpen]=useState(false),[step,setStep]=useState(0),[diet,setDiet]=useState("any"),[spice,setSpice]=useState("medium"),[taste,setTaste]=useState("savoury"),[budget,setBudget]=useState("any");
 const questions=[{title:"What’s your food preference?",description:"We’ll only suggest dishes that fit.",value:diet,set:setDiet,options:[["veg","Vegetarian","Vegetarian dishes; may contain dairy"],["any","Veg & non-veg","I’m open to both"]]}, {title:"How much heat do you like?",description:"From easy-going to a little fiery.",value:spice,set:setSpice,options:[["mild","Keep it mild","Flavour without the fire"],["medium","A little kick","Some spice is nice"],["hot","Bring the heat","I love spicy food"]]}, {title:"What are you craving?",description:"Follow your mood.",value:taste,set:setTaste,options:[["savoury","Something savoury","A snack or a satisfying meal"],["sweet","Something sweet","Dessert sounds perfect"],["refreshing","Something refreshing","A drink to cool things down"]]}, {title:"Your budget per dish?",description:"We’ll stay within it.",value:budget,set:setBudget,options:[["200","Up to ₹200","A little treat"],["350","Up to ₹350","Room for a favourite"],["500","Up to ₹500","Something special"],["any","No preference","Show me what fits my taste"]]}];
 const q=questions[Math.min(step,3)];const suggestions=recommend(menu.dishes,{diet,spice,taste,budget});
 return <><section className="taste-invite"><span className="taste-spark"><Sparkles size={24}/></span><div><h2>What are you in the mood for?</h2><p>A few quick questions. Dishes that fit your taste.</p></div><button className="primary" onClick={()=>{setStep(0);setOpen(true)}}>Find my flavour</button></section><Dialog open={open} onOpenChange={setOpen}><DialogContent className="taste-modal"><p className="eyebrow">YOUR PERSONAL MENU · {step<4?`${step+1} OF 4`:"THE RESULTS"}</p><DialogTitle>{step<4?q.title:"Made for your mood."}</DialogTitle><DialogDescription>{step<4?q.description:"Available dishes that come closest to your preferences."}</DialogDescription>{step<4?<><RadioGroup value={q.value} onValueChange={q.set} className="taste-options" aria-label={q.title}>{q.options.map(([value,title,desc])=><label key={value} className={q.value===value?"taste-option chosen":"taste-option"}><RadioGroupItem value={value}/><span><strong>{title}</strong><small>{desc}</small></span></label>)}</RadioGroup><div className="quiz-nav">{step>0&&<button className="secondary" onClick={()=>setStep(s=>s-1)}>Back</button>}<button className="primary" onClick={()=>setStep(s=>s+1)}>{step===3?"Find my dishes":"Continue"}</button></div></>:<><div className="recommendations">{suggestions.map(d=><button key={d.id} onClick={()=>{setOpen(false);onPick(d)}}><span className="match-label">{d.taste===taste&&d.spice===spice?"MATCHES YOUR TASTE":"ANOTHER OPTION"}</span><h3>{d.name}<span>₹{d.price}</span></h3><p>{d.description}</p><small>{d.veg?"Vegetarian":"Non-vegetarian"} · {d.spice} · {d.taste}</small></button>)}</div>{!suggestions.length&&<p>No available dishes fit your diet and budget right now. Try a different budget, or ask your server.</p>}<p className="quiz-note">Recommendations use the restaurant’s dish tags. Vegetarian does not mean vegan. For allergies or dietary restrictions, please check with your server.</p><button className="secondary" onClick={()=>setStep(0)}>Change my preferences</button></>}</DialogContent></Dialog></>
}
