"use client";
import {useState,useEffect} from "react";
import {Star,RefreshCw,MessageSquare} from "lucide-react";
type Review={id:string,rating:number,message:string,name:string,created_at:string,read_at:string|null};
export default function Reviews({restaurant}:{restaurant:string}){
 const [rows,setRows]=useState<Review[]>([]),[loading,setLoading]=useState(true),[more,setMore]=useState(false),[error,setError]=useState(""),[marking,setMarking]=useState<string|null>(null);
 async function load(append=false){setLoading(true);setError("");try{const r=await fetch(`/api/reviews?restaurant=${encodeURIComponent(restaurant)}&offset=${append?rows.length:0}`);const d=await r.json() as {reviews:Review[],hasMore:boolean,error?:string};if(!r.ok)throw Error(d.error);setRows(old=>append?[...old,...d.reviews.filter(n=>!old.some(o=>o.id===n.id))]:d.reviews);setMore(d.hasMore)}catch(e){setError(e instanceof Error?e.message:"Couldn’t load reviews")}finally{setLoading(false)}}
 useEffect(()=>{load()},[restaurant]);
 async function mark(id:string){setMarking(id);setError("");try{const r=await fetch("/api/reviews",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({restaurant,id})});const d=await r.json() as {error?:string,readAt:string};if(!r.ok)throw Error(d.error);setRows(old=>old.map(v=>v.id===id?{...v,read_at:d.readAt}:v))}catch(e){setError(e instanceof Error?e.message:"Couldn’t update review")}finally{setMarking(null)}}
 return <section className="reviews-inbox"><div className="list-heading"><div><h2>Customer reviews</h2><p>Private feedback, newest first.</p></div><button className="secondary" disabled={loading} onClick={()=>load()}><RefreshCw size={16}/>{loading?"Loading…":"Refresh"}</button></div>{error&&<p className="error" role="alert">{error}</p>}{!rows.length&&!loading&&!error&&<div className="empty"><MessageSquare size={32}/><h2>No reviews yet.</h2><p>Customers can leave a review from this restaurant’s menu.</p></div>}<div className="review-list">{rows.map(r=><article className={r.read_at?"manager-review":"manager-review unread"} key={r.id}><div className="review-topline"><div className="review-rating" aria-label={`${r.rating} out of 5 stars`}>{[1,2,3,4,5].map(n=><Star key={n} size={18} fill={n<=r.rating?"currentColor":"none"}/>)}<strong>{r.rating}/5</strong></div>{!r.read_at&&<span className="tiny-badge">NEW</span>}</div><p className="review-message">{r.message}</p><div className="review-byline"><div><strong>{r.name||"Anonymous guest"}</strong><time dateTime={r.created_at}>{new Date(r.created_at).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</time></div>{r.read_at?<span className="muted">Read</span>:<button className="secondary" disabled={marking!==null} onClick={()=>mark(r.id)}>{marking===r.id?"Updating…":"Mark as read"}</button>}</div></article>)}</div>{more&&<button className="secondary" disabled={loading} onClick={()=>load(true)}>{loading?"Loading…":"Load older reviews"}</button>}</section>
}
