"use client";
import {useEffect,useState} from "react";
import {Plus,Utensils,LockKeyhole,ExternalLink,Check,Settings2,QrCode,Users,Save,Pencil,Leaf,Store,Trash2,MessageSquare,ShoppingBag} from "lucide-react";
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Switch} from "@/components/ui/switch";
import {Toaster,toast} from "sonner";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {Sidebar,SidebarProvider} from "@/components/ui/sidebar";
import Sales from "./sales";
import Orders from "./orders";
import OrderAlerts from "./order-alerts";
import Waiters from "./waiters";
import Reviews from "./reviews";
import RestaurantAccess from "./restaurant-access";
import QRCode from "qrcode";
import type {Dish,Menu} from "@/lib/menu";
type Restaurant={id:string,name:string,active:boolean,count:number};
const blank:Dish={id:"",name:"",description:"",price:0,category:"Small plates",veg:true,available:true,secret:false,allergens:"",spice:"mild",taste:"savoury"};
export default function Team({owner,studio,email}:{owner:boolean,studio:boolean,email:string}){
 const [deleteOpen,setDeleteOpen]=useState(false),[deleteName,setDeleteName]=useState(""),[deleteError,setDeleteError]=useState(""),[deleting,setDeleting]=useState(false);
 const [restaurants,setRestaurants]=useState<Restaurant[]>([]),[id,setId]=useState(""),[menu,setMenu]=useState<Menu|null>(null),[revision,setRevision]=useState(0),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[dish,setDish]=useState<Dish|null>(null),[tab,setTab]=useState("menu"),[create,setCreate]=useState(false),[newName,setNewName]=useState(""),[slug,setSlug]=useState(""),[members,setMembers]=useState<{email:string}[]>([]),[member,setMember]=useState(""),[qr,setQr]=useState(""),[customerUrl,setCustomerUrl]=useState("");
 async function list(){const r=await fetch("/api/restaurants?admin=1"),d=await r.json() as any;if(!r.ok)throw Error(d.error);setRestaurants(d.restaurants);return d.restaurants as Restaurant[]}
 async function load(next:string){setError("");setMenu(null);try{const r=await fetch(`/api/menu?restaurant=${encodeURIComponent(next)}&admin=1`),d=await r.json() as any;if(!r.ok)throw Error(d.error);setMenu(d.menu);setRevision(d.revision);setDirty(false);}catch(e){setError(String(e instanceof Error?e.message:e))}}
 useEffect(()=>{list().then(rows=>{if(!rows.some(r=>r.id===id))setId(rows[0]?.id||"")}).catch(e=>setError(e.message))},[]);useEffect(()=>{if(!id){setError("");setMenu(null);setCustomerUrl("");setQr("");return;}load(id);const url=location.origin+"/r/"+id;setCustomerUrl(url);QRCode.toDataURL(url,{width:600,margin:4,color:{dark:"#17211b",light:"#ffffff"}}).then(setQr).catch(()=>setQr(""));},[id]);
 useEffect(()=>{function leave(e:BeforeUnloadEvent){if(dirty){e.preventDefault();e.returnValue=""}}window.addEventListener("beforeunload",leave);return()=>window.removeEventListener("beforeunload",leave)},[dirty]);
 function update(m:Menu){setMenu(m);setDirty(true)}
 async function save(){if(!menu)return;setBusy(true);setError("");try{const r=await fetch("/api/menu",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,menu,revision})}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setRevision(d.revision);setMenu(d.menu);setDirty(false);toast.success("Menu saved. Customers will see your latest changes.");await list()}catch(e){setError(e instanceof Error?e.message:"Couldn’t save") }finally{setBusy(false)}}
 async function addRestaurant(e:React.FormEvent){e.preventDefault();if(dirty){toast.error("Save the current menu before adding a restaurant.");return}setBusy(true);try{const r=await fetch("/api/restaurants",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:newName,id:slug})}),d=await r.json() as any;if(!r.ok)throw Error(d.error);await list();setId(d.id);setCreate(false);setNewName("");setSlug("");setTab("menu");toast.success("Restaurant added")}catch(e){toast.error(e instanceof Error?e.message:"Couldn’t add restaurant")}finally{setBusy(false)}}
 async function teamLoad(){const r=await fetch("/api/team"),d=await r.json() as any;if(!r.ok)throw Error(d.error);setMembers(d.members)}
 async function teamChange(email:string,action:string){try{const r=await fetch("/api/team",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,action})}),d=await r.json() as any;if(!r.ok)throw Error(d.error);setMember("");await teamLoad();toast.success(action==="add"?"Team access added":"Team access removed")}catch(e){toast.error(e instanceof Error?e.message:"Couldn’t update team")}}
 async function deleteRestaurant(){
 setDeleting(true);setDeleteError("");
 try{
  const response=await fetch("/api/restaurants",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,revision,confirmation:deleteName})});
  const result=await response.json() as {error?:string};if(!response.ok)throw Error(result.error||"Couldn’t delete restaurant");
  const remaining=restaurants.filter(r=>r.id!==id);setRestaurants(remaining);setDirty(false);setMenu(null);setError("");setDeleteOpen(false);setId(remaining[0]?.id||"");setTab("menu");toast.success("Restaurant deleted. Its customer menu is no longer available.");
 }catch(e){setDeleteError(e instanceof Error?e.message:"Couldn’t delete restaurant")}finally{setDeleting(false)}
 }
 const savedName=restaurants.find(r=>r.id===id)?.name||"";
 const nav=[{key:"sales",label:"Monthly sales",icon:ShoppingBag},{key:"orders",label:"Orders & alerts",icon:ShoppingBag},{key:"waiters",label:"Manage waiters",icon:Users},{key:"menu",label:"Menu manager",icon:Utensils},{key:"reviews",label:"Customer reviews",icon:MessageSquare},{key:"settings",label:"Restaurant details",icon:Settings2},{key:"qr",label:"QR & customer link",icon:QrCode},...(studio&&id?[{key:"restaurant-access",label:"Restaurant access",icon:Users}]:[]),...(owner?[{key:"team",label:"Studio team access",icon:Users}]:[])];
 return <SidebarProvider className="admin"><Toaster richColors/><Sidebar collapsible="none" className="admin-sidebar"><a className="brand" href="/"><span className="brandmark"><Utensils size={20}/></span><span>AS 426<small>STUDIOS</small></span></a><p className="sidebar-label">RESTAURANTS <span>{restaurants.length}</span></p><div className="restaurant-list">{restaurants.map(r=><button className={id===r.id?"restaurant-option active":"restaurant-option"} key={r.id} onClick={()=>{if(dirty){toast.error("Save your changes before switching restaurants.");return}setId(r.id);setTab("menu")}}><Store size={16}/><span>{r.name}<small>{r.active?"Live menu":"Paused"} · {r.count} dishes</small></span></button>)}</div>{studio&&<button className="add-restaurant" onClick={()=>setCreate(true)}><Plus size={16}/> Add restaurant</button>}<div className="sidebar-divider"/>{nav.map(n=><button className={tab===n.key?"nav-item active":"nav-item"} key={n.key} onClick={()=>{setTab(n.key);if(n.key==="team")teamLoad().catch(e=>toast.error(e.message))}}><n.icon size={18}/>{n.label}</button>)}<div className="sidebar-account"><span className="avatar">AS</span><div>{owner?"Workspace owner":studio?"Studio team":"Restaurant manager"}<small>{email}</small></div></div></Sidebar><div className="admin-main"><header className="admin-top"><span>Workspace <span className="muted"> / {menu?.name||"Restaurant"}</span></span>{id&&<a href={"/r/"+id} target="_blank" rel="noreferrer">View customer menu <ExternalLink size={15}/></a>}</header><main className="admin-content"><OrderAlerts managerOnly onOpen={next=>{if(dirty){toast.error("Save your menu changes before switching to orders.");return}setId(next);setTab("orders")}}/><div className="admin-title"><div><p className="eyebrow">AS 426 STUDIOS · RESTAURANT WORKSPACE</p><h1>{nav.find(n=>n.key===tab)?.label}</h1><p>{tab==="orders"?"Keep every table moving.":tab==="waiters"?"Give your team the access they need.":tab==="menu"?"A fresh menu, always within reach.":tab==="reviews"?"Hear from the people at your tables.":tab==="settings"?"Make this experience their own.":tab==="qr"?"One scan. Their next favourite dish.":"The right people, behind every menu."}</p></div>{menu&&tab!=="team"&&tab!=="restaurant-access"&&tab!=="reviews"&&tab!=="orders"&&tab!=="waiters"&&tab!=="sales"&&<button className="primary" onClick={save} disabled={!dirty||busy}><Save size={16}/>{busy?"Saving…":dirty?"Save changes":"All changes saved"}</button>}</div>{error&&<div className="error" role="alert">{error} {!menu&&<button onClick={()=>load(id)}>Retry</button>}</div>}
 {!id&&!error&&<div className="empty"><h2>No restaurants yet.</h2><p>Add a restaurant to create its menu and QR code.</p>{studio&&<button className="primary" onClick={()=>setCreate(true)}><Plus size={16}/>Add restaurant</button>}</div>}
 {menu&&tab==="menu"&&<><div className="stats"><div><span>On the menu</span><strong>{menu.dishes.length}<small>dishes</small></strong></div><div><span>Ready to serve</span><strong>{menu.dishes.filter(d=>d.available).length}<small>available</small></strong></div><div><span>A little mystery</span><strong>{menu.dishes.filter(d=>d.secret).length}<small>secret dishes</small></strong></div></div><div className="list-heading"><div><h2>Your dishes</h2><p>Changes go live when you save.</p></div><button className="primary" onClick={()=>setDish({...blank,id:crypto.randomUUID()})}><Plus size={16}/>Add dish</button></div><div className="admin-dishes">{menu.dishes.map(d=><div className="admin-dish" key={d.id}><span className={d.secret?"dish-icon secret":"dish-icon"}>{d.secret?<LockKeyhole size={20}/>:<Utensils size={20}/>}</span><div className="admin-dish-name"><h3>{d.name} {d.secret&&<span className="tiny-badge">SECRET</span>}</h3><p>{d.category} · {d.veg?"Vegetarian":"Non-vegetarian"}</p></div><strong>₹{d.price}</strong><label className="availability"><Switch aria-label={`${d.name} available`} checked={d.available} onCheckedChange={v=>update({...menu,dishes:menu.dishes.map(x=>x.id===d.id?{...x,available:v}:x)})}/><span>{d.available?"Available":"Sold out"}</span></label><button className="icon-button" aria-label={`Edit ${d.name}`} onClick={()=>setDish({...d})}><Pencil size={17}/></button></div>)}</div>{!menu.dishes.length&&<div className="empty"><h2>A new menu starts here.</h2><p>Add the first dish to bring this restaurant to life.</p></div>}<div className="tip"><LockKeyhole size={22}/><div><strong>Give them something to discover.</strong><p>Mark a dish as secret to put it behind the customer’s “Unlock the secret” button.</p></div></div></>}
 {menu&&tab==="settings"&&<div className="form-panel"><label>Restaurant name<input value={menu.name} maxLength={70} onChange={e=>update({...menu,name:e.target.value})}/></label><label>Welcome line<input value={menu.tagline} maxLength={120} onChange={e=>update({...menu,tagline:e.target.value})}/></label><label>Menu note / tax and allergy information<textarea value={menu.note} maxLength={200} onChange={e=>update({...menu,note:e.target.value})}/></label><label className="switch-label"><Switch checked={menu.active} onCheckedChange={v=>update({...menu,active:v})}/>Customer menu {menu.active?"live":"paused"}</label><p className="muted">Pausing hides this restaurant’s menu from customers. Its link and dishes are kept.</p><label>Permanent menu path<input readOnly value={"/r/"+id}/></label>{studio&&<div className="delete-zone"><h2>Delete restaurant</h2><p>Permanently remove this restaurant and all its dishes. Its customer menu and QR link will stop working.</p><button className="delete-button" disabled={busy} onClick={()=>{setDeleteName("");setDeleteError("");setDeleteOpen(true)}}><Trash2 size={16}/>Delete restaurant</button></div>}</div>}
 {tab==="qr"&&<div className="qr-panel"><div className="qr-card"><p className="eyebrow">{menu?.name}</p><h2>Your table<br/>has a secret.</h2>{qr&&<img src={qr} alt={`QR code for ${menu?.name}'s menu`}/>}<p>Scan. Discover. Enjoy.</p><small>BY AS 426 STUDIOS</small></div><div><h2>Bring the menu to the table.</h2><p>Place this QR on table cards, bills or takeaway packaging. Menu edits keep the same link.</p><label>Customer menu link<input readOnly value={customerUrl}/></label><div className="button-row"><button className="primary" onClick={()=>navigator.clipboard.writeText(customerUrl).then(()=>toast.success("Link copied")).catch(()=>toast.error("Select and copy the link above."))}>Copy link</button>{qr&&<a className="secondary" href={qr} download={`${id}-qr.png`}>Download QR</a>}</div><p className="muted">Test access on a customer’s phone before printing. The preview is private until sharing is enabled. Connect your final domain before printing QR cards.</p></div></div>}
 {id&&tab==="sales"&&<Sales key={id} restaurant={id}/> }
 {id&&tab==="orders"&&<Orders key={id} restaurant={id} canEdit/>}
 {id&&tab==="waiters"&&<Waiters key={id} restaurant={id}/>}
 {id&&tab==="reviews"&&<Reviews key={id} restaurant={id}/>}
 {studio&&id&&tab==="restaurant-access"&&<RestaurantAccess key={id} restaurant={id} name={menu?.name||savedName}/>}
 {tab==="team"&&<div className="form-panel"><h2>Manage your studio team</h2><p>Studio team members can manage every restaurant and assign restaurant managers. To give access to just one restaurant, select it and choose Restaurant access. Only you can change studio-wide access.</p><form onSubmit={e=>{e.preventDefault();teamChange(member,"add")}}><label>Teammate’s sign-in email<input type="email" required value={member} onChange={e=>setMember(e.target.value)} placeholder="name@example.com"/></label><button className="primary" type="submit"><Plus size={16}/>Add team member</button></form><p className="muted">This grants dashboard access; no invitation is sent. Members must sign in with this email, and the site’s sharing settings must also allow them to open it.</p>{members.map(m=><div className="member-row" key={m.email}><span>{m.email}</span><button onClick={()=>teamChange(m.email,"remove")}>Remove access</button></div>)}</div>}
 </main></div>
 <AlertDialog open={deleteOpen} onOpenChange={v=>{if(!deleting)setDeleteOpen(v)}}><AlertDialogContent className="editor-modal"><AlertDialogTitle>Delete {savedName}?</AlertDialogTitle><AlertDialogDescription>This permanently removes the restaurant, all its dishes and any unsaved changes. Its QR link will no longer show a menu. This cannot be undone.</AlertDialogDescription><label>Type <strong>{savedName}</strong> to confirm<input autoComplete="off" value={deleteName} disabled={deleting} onChange={e=>setDeleteName(e.target.value)}/></label>{deleteError&&<p className="error" role="alert">{deleteError}</p>}<AlertDialogFooter><AlertDialogCancel disabled={deleting}>Keep restaurant</AlertDialogCancel><AlertDialogAction className="delete-button" disabled={deleting||busy||!savedName||deleteName!==savedName} onClick={e=>{e.preventDefault();deleteRestaurant()}}>{deleting?"Deleting…":"Delete restaurant"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={!!dish} onOpenChange={v=>!v&&setDish(null)}><DialogContent className="editor-modal"><DialogTitle>{menu?.dishes.some(d=>d.id===dish?.id)?"Edit dish":"Add a dish"}</DialogTitle><DialogDescription>Save the menu after editing to publish your changes.</DialogDescription>{dish&&<form onSubmit={e=>{e.preventDefault();if(!menu)return;update({...menu,dishes:menu.dishes.some(d=>d.id===dish.id)?menu.dishes.map(d=>d.id===dish.id?dish:d):[...menu.dishes,dish]});setDish(null)}}><label>Dish name<input required maxLength={100} value={dish.name} onChange={e=>setDish({...dish,name:e.target.value})}/></label><label>Description<textarea maxLength={350} value={dish.description} onChange={e=>setDish({...dish,description:e.target.value})}/></label><div className="form-row"><label>Price (₹)<input type="number" required min="0" max="100000" step="0.01" value={dish.price} onChange={e=>setDish({...dish,price:Number(e.target.value)})}/></label><label>Category<input required maxLength={40} list="categories" value={dish.category} onChange={e=>setDish({...dish,category:e.target.value})}/><datalist id="categories">{[...new Set(menu?.dishes.map(d=>d.category))].map(c=><option key={c} value={c}/>)}</datalist></label></div><label>Allergens<input maxLength={150} value={dish.allergens} onChange={e=>setDish({...dish,allergens:e.target.value})} placeholder="e.g. Milk, nuts, wheat"/></label><div className="taste-fields"><fieldset><legend>Spice level</legend><RadioGroup value={dish.spice} onValueChange={v=>setDish({...dish,spice:v as Dish["spice"]})} className="radio-options">{["mild","medium","hot"].map(v=><label key={v}><RadioGroupItem value={v}/>{v}</label>)}</RadioGroup></fieldset><fieldset><legend>Flavour</legend><RadioGroup value={dish.taste} onValueChange={v=>setDish({...dish,taste:v as Dish["taste"]})} className="radio-options">{["savoury","sweet","refreshing"].map(v=><label key={v}><RadioGroupItem value={v}/>{v}</label>)}</RadioGroup></fieldset></div><div className="toggle-row"><label><Switch checked={dish.veg} onCheckedChange={v=>setDish({...dish,veg:v})}/>Vegetarian</label><label><Switch checked={dish.secret} onCheckedChange={v=>setDish({...dish,secret:v})}/>Secret dish</label><label><Switch checked={dish.available} onCheckedChange={v=>setDish({...dish,available:v})}/>Available</label></div><div className="button-row"><button className="primary" type="submit">Keep changes</button>{menu?.dishes.some(d=>d.id===dish.id)&&<button className="danger" type="button" onClick={()=>{if(menu)update({...menu,dishes:menu.dishes.filter(d=>d.id!==dish.id)});setDish(null);toast("Dish removed from draft. Save to publish.")}}>Remove from menu</button>}</div></form>}</DialogContent></Dialog>
 <Dialog open={create} onOpenChange={setCreate}><DialogContent className="editor-modal"><DialogTitle>Add a restaurant</DialogTitle><DialogDescription>A separate menu and QR code for your next client.</DialogDescription><form onSubmit={addRestaurant}><label>Restaurant name<input required maxLength={70} value={newName} onChange={e=>{setNewName(e.target.value);setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,60))}} placeholder="e.g. The Green Fork"/></label><label>Unique menu URL<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={60} value={slug} onChange={e=>setSlug(e.target.value)}/><small>/r/{slug||"restaurant-name"}</small></label><button className="primary" disabled={busy}>{busy?"Creating…":"Create restaurant"}</button></form></DialogContent></Dialog>
 </SidebarProvider>
}
